Repository WildCodeSchool/202209-orleans-php-project-labanquepostale, pull requests merged in 2022-12, with the labels that each got.

#7 PR d'initialisation
  assets/app.js
  assets/styles/_wcs.scss
  assets/styles/app.scss
  assets/styles/theme.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  yarn.lock
Labels: Reviewed

#50 S01 us06 home page
  assets/images/header.jpeg
  assets/styles/app.scss
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#43 title-lesson
  assets/styles/theme.scss
  composer.json
  composer.lock
  migrations/Version20221214160154.php
  src/Controller/LessonController.php
  src/DataFixtures/LessonFixtures.php
  src/Entity/Lesson.php
  src/Repository/LessonRepository.php
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Conflicts resolved

#48 S0 us#1 navbar
  assets/styles/theme.scss
  templates/base.html.twig
  templates/component/_navbar.html.twig
  templates/layout.html.twig
Labels: Reviewed, Conflicts resolved

#53 S1 us#5 header
  assets/images/Logo.png
  assets/styles/theme.scss
  templates/base.html.twig
  templates/component/_header.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Conflicts resolved, Corrections Done

#58 integrate video on each lesson page
  src/DataFixtures/LessonFixtures.php
  templates/lesson/show.html.twig
Labels: Reviewed

#62 Fix_header_add on space for title:col-8
  templates/component/_header.html.twig
Labels: Reviewed, Fix

#63 fix/settitile
  templates/lesson/show.html.twig
Labels: Reviewed

#64 Dev To Main
  assets/app.js
  assets/images/Logo.png
  assets/images/header.jpeg
  assets/styles/_wcs.scss
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/theme.scss
  composer.json
  composer.lock
  migrations/Version20221214160154.php
  package.json
  src/Controller/LessonController.php
  src/DataFixtures/LessonFixtures.php
  src/Entity/Lesson.php
  src/Repository/LessonRepository.php
  templates/base.html.twig
  templates/component/_header.html.twig
  templates/component/_navbar.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  yarn.lock
Labels: Reviewed

#61 takout_navbar de welcome page
  templates/component/_header.html.twig
  templates/component/_navbar.html.twig
Labels: Reviewed, Conflicts resolved

#70 updates one on padding
  templates/component/_header.html.twig
Labels: Reviewed, Conflicts resolved

#60 US35_page_lesson
  assets/styles/home.scss
  assets/styles/lesson.scss
  assets/styles/theme.scss
  src/DataFixtures/LessonFixtures.php
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  webpack.config.js
Labels: Reviewed, Conflicts resolved

#55 S01 US04 : Afficher questions du quiz
  migrations/Version20221219210141.php
  src/Controller/LessonController.php
  src/DataFixtures/LessonFixtures.php
  src/DataFixtures/QuestionFixtures.php
  src/Entity/Lesson.php
  src/Entity/Question.php
  src/Repository/QuestionRepository.php
  templates/Components/_quiz.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Conflicts resolved

#77 some modif on home page
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Conflicts resolved

#78 reajust the size of the lesson video
  templates/lesson/show.html.twig
Labels: Reviewed
