Repository WildCodeSchool/202209-orleans-php-project-labanquepostale, pull requests merged in 2023-01, with the labels that each got.

#80 remove navbar of the welcome page
  templates/home/index.html.twig
Labels: Reviewed, Fix

#81 fixtitle
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#79 page/tutorial
  assets/styles/theme.scss
  migrations/Version20221221160144.php
  src/Controller/LessonController.php
  src/Controller/TutorialController.php
  src/DataFixtures/LessonFixtures.php
  src/DataFixtures/QuestionFixtures.php
  src/DataFixtures/TutorialFixtures.php
  src/Entity/Lesson.php
  src/Entity/Tutorial.php
  src/Repository/TutorialRepository.php
  templates/component/_header.html.twig
  templates/component/_navbar.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Conflicts resolved

#88 Fix header svg
  templates/component/_header.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Conflicts resolved

#93 Merge dev to main
  assets/styles/home.scss
  assets/styles/lesson.scss
  assets/styles/theme.scss
  migrations/Version20221219210141.php
  migrations/Version20221221160144.php
  src/Controller/LessonController.php
  src/Controller/TutorialController.php
  src/DataFixtures/LessonFixtures.php
  src/DataFixtures/QuestionFixtures.php
  src/DataFixtures/TutorialFixtures.php
  src/Entity/Lesson.php
  src/Entity/Question.php
  src/Entity/Tutorial.php
  src/Repository/QuestionRepository.php
  src/Repository/TutorialRepository.php
  templates/Components/_quiz.html.twig
  templates/component/_header.html.twig
  templates/component/_navbar.html.twig
  templates/home/index.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/tutorial/index.html.twig
  webpack.config.js
Labels: Reviewed

#87 Fix svg navbar
  templates/component/_navbar.html.twig
Labels: Reviewed, Conflicts resolved

#90 S02 us032 login
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/login.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/packages/translation.yaml
  migrations/Version20230101200522.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/home/index.html.twig
  templates/login/index.html.twig
Labels: Reviewed, Conflicts resolved

#94 S01 US34 : Afficher les réponses du quiz
  migrations/Version20221220155148.php
  src/Controller/LessonController.php
  src/DataFixtures/LessonFixtures.php
  src/DataFixtures/QuestionFixtures.php
  src/DataFixtures/ResponseFixtures.php
  src/Entity/Question.php
  src/Entity/Response.php
  src/Form/LessonType.php
  src/Form/QuestionType.php
  src/Form/ResponseType.php
  src/Repository/ResponseRepository.php
  templates/Components/_quiz.html.twig
  templates/base.html.twig
  templates/components/_header.html.twig
  templates/components/_navbar.html.twig
  templates/components/_quiz.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Conflicts resolved

#97 S01 US35 : savoir si j'ai fait le quiz
  migrations/Version20230105113045.php
  src/Controller/LessonController.php
  src/Entity/Lesson.php
  src/Entity/User.php
  src/Form/LessonType.php
Labels: Reviewed, To review

#101 US38 style page tutorial
  assets/styles/lesson.scss
  templates/login/index.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed

#100 S02 us31 registration
  assets/styles/app.scss
  assets/styles/registration.scss
  config/packages/twig.yaml
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#102 Fix Login
  config/packages/security.yaml
  src/Controller/LoginController.php
  templates/components/_navbar.html.twig
  templates/login/index.html.twig
Labels: Reviewed, Conflicts resolved

#103 dev to main
  Dockerfile
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/lesson.scss
  assets/styles/login.scss
  assets/styles/registration.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  migrations/Version20221220155148.php
  migrations/Version20230101200522.php
  migrations/Version20230105113045.php
  src/Controller/LessonController.php
  src/Controller/LoginController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/LessonFixtures.php
  src/DataFixtures/QuestionFixtures.php
  src/DataFixtures/ResponseFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Lesson.php
  src/Entity/Question.php
  src/Entity/Response.php
  src/Entity/User.php
  src/Form/LessonType.php
  src/Form/QuestionType.php
  src/Form/RegistrationFormType.php
  src/Form/ResponseType.php
  src/Repository/ResponseRepository.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/Components/_quiz.html.twig
  templates/base.html.twig
  templates/component/_navbar.html.twig
  templates/components/_header.html.twig
  templates/components/_navbar.html.twig
  templates/components/_quiz.html.twig
  templates/home/index.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed

#122 S03_US09 : Page d'accueil admin
  assets/styles/admin.scss
  src/Controller/AdminController.php
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/components/_headerAdmin.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/registration/register.html.twig
  templates/tutorial/index.html.twig
  webpack.config.js
Labels: Reviewed

#124 Layout admin
  templates/admin/index.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed

#125 change the main colors and background
  assets/styles/theme.scss
  templates/base.html.twig
  templates/components/_header.html.twig
Labels: Reviewed, Corrections Done

#126 Us37 sp03 ValidationQuizz
  assets/styles/lesson.scss
  migrations/Version20230116183243.php
  src/Controller/LessonController.php
  src/DataFixtures/ResponseFixtures.php
  src/Entity/Explanation.php
  src/Entity/Question.php
  src/Form/QuestionType.php
  src/Form/ResponseType.php
  src/Repository/ExplanationRepository.php
  templates/components/_quiz.html.twig
Labels: Reviewed

#127 Fixed CSS files
  assets/styles/app.scss
  assets/styles/home.scss
  templates/home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/lesson/index.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/tutorial/index.html.twig
  webpack.config.js
Labels: Reviewed, Fix

#130 redesign the home page
  assets/styles/home.scss
  assets/styles/theme.scss
  templates/home/index.html.twig
Labels: Reviewed, Conflicts resolved

#129 Fix style login page
  assets/styles/login.scss
  templates/components/_header.html.twig
  templates/login/index.html.twig
Labels: Reviewed, Conflicts resolved

#134 Us40style lesson
  assets/styles/lesson.scss
  src/Controller/LessonController.php
  templates/lesson/index.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed

#144 some change on the registration page
  assets/styles/registration.scss
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: Reviewed

#141 S03 US17 : Création leçon admin
  migrations/Version20221221160144.php
  src/Controller/AdminLessonController.php
  src/Entity/Lesson.php
  src/Form/Lesson1Type.php
  templates/admin_lesson/_delete_form.html.twig
  templates/admin_lesson/_form.html.twig
  templates/admin_lesson/edit.html.twig
  templates/admin_lesson/index.html.twig
  templates/admin_lesson/new.html.twig
  templates/admin_lesson/show.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed, To review

#128 Fix navbar round
  assets/styles/app.scss
  assets/styles/theme.scss
  templates/base.html.twig
  templates/components/_navbar.html.twig
  templates/home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Conflicts resolved, Corrections Done

#145 S03 US18 : Éditer une leçon
  src/Controller/AdminLessonController.php
  src/Controller/AdminTutorialController.php
  templates/admin_lesson/edit.html.twig
Labels: Reviewed

#150 fix on the return button
  templates/components/_header.html.twig
Labels: Reviewed

#151 reduce the size of each button text and label
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#155 Fix style page quiz
  assets/styles/lesson.scss
  assets/styles/quiz.scss
  assets/styles/theme.scss
  templates/components/_quiz.html.twig
  templates/lesson/show.html.twig
  webpack.config.js
Labels: Reviewed, Fix

#173 modif size of text on login et registration page
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#175 reduce the width of home buttons
  templates/home/index.html.twig
Labels: Reviewed

#178 Fix : Card entièrement cliquable
  assets/styles/lesson.scss
Labels: Reviewed

#180 US40 disocier leçons faites/pas faites
  assets/styles/lesson.scss
  templates/lesson/index.html.twig
Labels: Reviewed

#181 fixed the navbar
  assets/styles/lesson.scss
  templates/components/_navbar.html.twig
Labels: Reviewed, Conflicts resolved

#185 Fix Role Admin
  config/packages/security.yaml
Labels: Reviewed

#188 Fix US23
  src/Controller/AdminLessonController.php
  src/Controller/AdminTutorialController.php
  src/Entity/Lesson.php
  src/Form/LessonType.php
  templates/admin_lesson/_delete_form.html.twig
  templates/admin_lesson/edit.html.twig
  templates/admin_lesson/index.html.twig
  templates/admin_lesson/new.html.twig
  templates/admin_tutorial/index.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed, Fix, Corrections Done

#176 Creation on the page profil
  assets/images/profil.png
  assets/styles/profil.scss
  src/Controller/ProfilController.php
  templates/components/_navbar.html.twig
  templates/profil/profil.html.twig
  webpack.config.js
Labels: Reviewed, Corrections Done

#182 S03 US10 : Administrer les quiz par leçon
  assets/styles/admin.scss
  migrations/Version20230125092653.php
  src/Controller/AdminQuestionController.php
  src/Entity/Lesson.php
  src/Form/LessonType.php
  src/Form/QuestionType.php
  src/Form/QuizQuestionType.php
  templates/admin_lesson/_delete_form.html.twig
  templates/admin_lesson/_form.html.twig
  templates/admin_question/_delete_form.html.twig
  templates/admin_question/_form.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_question/index.html.twig
  templates/admin_question/new.html.twig
  templates/admin_question/show.html.twig
  templates/admin_tutorial/_delete_form.html.twig
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/admin_tutorial/quiz_index.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Conflicts resolved

#190 Fix cards
  assets/styles/lesson.scss
  templates/lesson/index.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Corrections Done

#191 fix header
  assets/styles/theme.scss
  templates/components/_header.html.twig
Labels: Reviewed

#194 S03 US11 : Créer une question et ses réponses
  assets/controllers.json
  composer.json
  composer.lock
  config/bundles.php
  config/routes/ux_live_component.yaml
  package.json
  src/Controller/AdminQuestionController.php
  src/Entity/Explanation.php
  src/Entity/Question.php
  src/Form/ExplanationType.php
  src/Form/QuestionType.php
  src/Twig/Components/AdminQuizComponent.php
  symfony.lock
  templates/admin_question/_form.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_question/new.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/admin_tutorial/quiz_index.html.twig
  templates/components/_form_collection_question.html.twig
  yarn.lock
Labels: Reviewed

#196 Fix bug quiz
  src/Controller/LessonController.php
  src/Form/QuizLessonType.php
  src/Form/QuizQuestionType.php
  templates/components/_quiz.html.twig
Labels: Reviewed, Fix

#198 Dev to main 26/01
  assets/controllers.json
  assets/images/profil.png
  assets/styles/admin.scss
  assets/styles/lesson.scss
  assets/styles/profile.scss
  assets/styles/quiz.scss
  assets/styles/theme.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/routes/ux_live_component.yaml
  migrations/Version20230125092653.php
  package.json
  src/Controller/AdminLessonController.php
  src/Controller/AdminQuestionController.php
  src/Controller/AdminTutorialController.php
  src/Controller/LessonController.php
  src/Controller/ProfileController.php
  src/Entity/Explanation.php
  src/Entity/Lesson.php
  src/Entity/Question.php
  src/Form/ExplanationType.php
  src/Form/Lesson1Type.php
  src/Form/LessonType.php
  src/Form/QuestionType.php
  src/Form/QuizLessonType.php
  src/Form/QuizQuestionType.php
  src/Twig/Components/AdminQuizComponent.php
  symfony.lock
  templates/admin_lesson/_delete_form.html.twig
  templates/admin_lesson/_form.html.twig
  templates/admin_lesson/edit.html.twig
  templates/admin_lesson/new.html.twig
  templates/admin_lesson/show.html.twig
  templates/admin_question/_delete_form.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_question/index.html.twig
  templates/admin_question/new.html.twig
  templates/admin_question/show.html.twig
  templates/admin_tutorial/_delete_form.html.twig
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/index.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/admin_tutorial/quiz_index.html.twig
  templates/admin_tutorial/show.html.twig
  templates/components/_form_collection_question.html.twig
  templates/components/_header.html.twig
  templates/components/_navbar.html.twig
  templates/components/_quiz.html.twig
  templates/home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/login/index.html.twig
  templates/profile/profile.html.twig
  templates/registration/register.html.twig
  templates/tutorial/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#199 add icon on each button on admin tutorial page
  templates/admin_tutorial/index.html.twig
Labels: Reviewed, Fix

#200 S03 US12 : Éditer et supprimer un quiz
  src/Controller/AdminQuestionController.php
  templates/admin_question/_delete_form.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_tutorial/quiz_index.html.twig
Labels: Reviewed

#195 add wysiwyg
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  package.json
  src/Form/LessonType.php
  symfony.lock
  webpack.config.js
  yarn.lock
Labels: Reviewed, Conflicts resolved

#204 Dev to main 27/01
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  package.json
  src/Controller/AdminQuestionController.php
  src/Form/LessonType.php
  symfony.lock
  templates/admin_question/_delete_form.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_tutorial/index.html.twig
  templates/admin_tutorial/quiz_index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#203 S04 us#43 image upload
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20230126231930.php
  public/uploads/.gitignore
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/userImages/profileAdmin.jpeg
  src/DataFixtures/userImages/profileUser.jpg
  src/Entity/User.php
  src/Form/ProfileType.php
  symfony.lock
  templates/profile/profile.html.twig
Labels: Reviewed, Conflicts resolved

#202 US41CheckAnswerIsTrue
  src/Controller/LessonController.php
  src/Repository/ExplanationRepository.php
  src/Service/CheckGoodAnswer.php
  templates/base.html.twig
  templates/components/_quiz.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Conflicts resolved

#211 fixSizeCards
  templates/lesson/index.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix

#212 Fix_LessonsDone
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix

#216 Fix Orthographe
  src/DataFixtures/QuestionFixtures.php
  templates/home/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Fix

#213 Fix URL nommage
  src/Controller/AdminLessonController.php
  src/Controller/AdminQuestionController.php
  src/Controller/AdminTutorialController.php
  src/Controller/LessonController.php
  src/Controller/ProfileController.php
  src/Controller/TutorialController.php
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix, Conflicts resolved

#218 US #44 : "Leçon validée" sur la card en plus de la pastille
  templates/lesson/index.html.twig
Labels: Reviewed, Conflicts resolved

#219 S05 us#43 profile form
  assets/styles/profile.scss
  src/Controller/ProfileController.php
  src/Entity/User.php
  src/Form/ProfileType.php
  templates/profile/profile.html.twig
  templates/profile/profile_form.html.twig
Labels: Reviewed

#220 Fix Chemin admin
  templates/components/_headerAdmin.html.twig
  templates/login/index.html.twig
Labels: Reviewed, Fix

#221 Fix US44
  templates/lesson/index.html.twig
Labels: Reviewed, Fix

#222 Fix Route qui ne marche pas
  src/Controller/LessonController.php
Labels: Reviewed, Fix

#224 Dev to main 30/01 15h
  assets/styles/profile.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20230126231930.php
  public/uploads/.gitignore
  src/Controller/AdminLessonController.php
  src/Controller/AdminQuestionController.php
  src/Controller/AdminTutorialController.php
  src/Controller/LessonController.php
  src/Controller/ProfileController.php
  src/Controller/TutorialController.php
  src/DataFixtures/QuestionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/userImages/profileAdmin.jpeg
  src/DataFixtures/userImages/profileUser.jpg
  src/Entity/User.php
  src/Form/ProfileType.php
  src/Repository/ExplanationRepository.php
  src/Service/CheckGoodAnswer.php
  symfony.lock
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/base.html.twig
  templates/components/_headerAdmin.html.twig
  templates/components/_quiz.html.twig
  templates/home/index.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/login/index.html.twig
  templates/profile/profile.html.twig
  templates/profile/profile_form.html.twig
  templates/registration/register.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed

#223 ajout icone sur les boutons coté admin
  templates/admin_lesson/_delete_form.html.twig
  templates/admin_lesson/_form.html.twig
  templates/admin_lesson/edit.html.twig
  templates/admin_question/_delete_form.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_tutorial/_delete_form.html.twig
  templates/admin_tutorial/_form.html.twig
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/index.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/admin_tutorial/quiz_index.html.twig
Labels: Reviewed, Conflicts resolved

#246 mentionsLegales
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix

#247 stylefixCards
  assets/styles/lesson.scss
  templates/tutorial/index.html.twig
Labels: Reviewed

#251 progressProfil
  assets/styles/profile.scss
  src/Controller/ProfileController.php
  templates/profile/profile.html.twig
Labels: Reviewed

#250 Pages d'erreur
  templates/bundles/TwigBundle/Exception/error400.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Reviewed, To review

#252 Dev to main 31/01 12h
  assets/styles/home.scss
  assets/styles/lesson.scss
  assets/styles/profile.scss
  src/Controller/ProfileController.php
  src/Entity/User.php
  templates/admin_lesson/_delete_form.html.twig
  templates/admin_lesson/_form.html.twig
  templates/admin_lesson/edit.html.twig
  templates/admin_question/_delete_form.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_tutorial/_delete_form.html.twig
  templates/admin_tutorial/_form.html.twig
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/index.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/admin_tutorial/quiz_index.html.twig
  templates/bundles/TwigBundle/Exception/error400.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/home/index.html.twig
  templates/profile/profile.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed

#253 fixMessageFlash
  templates/base.html.twig
  templates/components/_quiz.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed

#254 Fix - Titres onglets et favicon
  templates/admin_lesson/edit.html.twig
  templates/admin_lesson/new.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_question/index.html.twig
  templates/admin_question/new.html.twig
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/index.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/admin_tutorial/new.html.twig
  templates/admin_tutorial/quiz_index.html.twig
  templates/base.html.twig
  templates/bundles/TwigBundle/Exception/error400.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix

#256 Fix - Ajout tutoriel et couleur messages flash
  src/Controller/AdminLessonController.php
  src/Controller/AdminQuestionController.php
  src/Controller/AdminTutorialController.php
  templates/admin_tutorial/quiz_index.html.twig
Labels: Reviewed, Fix

#257 Fix layout progressbar
  assets/styles/profile.scss
  templates/profile/profile.html.twig
  templates/profile/profile_form.html.twig
Labels: Reviewed, Fix

#259 redirect with the logo
  templates/components/_header.html.twig
Labels: Reviewed, Fix

#255 stylization of quiz page
  assets/styles/quiz.scss
  assets/styles/theme.scss
  templates/components/_quiz.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Conflicts resolved
