Repository WildCodeSchool/202209-orleans-php-project-labanquepostale, pull requests merged in 2023-02, with the labels that each got.

#261 Ajouté filtre raw pour échapper les balises html
  templates/lesson/show.html.twig
Labels: Reviewed, Fix

#263 fixProfil
  assets/styles/profile.scss
Labels: Reviewed, Fix

#264 fixNav
  templates/components/_navbar.html.twig
Labels: Reviewed, Fix

#266 Fix Réponses
  src/Controller/LessonController.php
Labels: Reviewed, Fix

#267 Fix messages flash sur toutes les pages
  templates/base.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/profile/profile.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix

#268 edit on button
  templates/profile/profile.html.twig
Labels: Reviewed, Fix

#271 add an admin button
  templates/components/_header.html.twig
Labels: Reviewed, Fix

#272 remove tab lesson and quiz admin
  templates/layoutAdmin.html.twig
Labels: Reviewed, Fix

#273 cascade/admin
  src/Entity/Lesson.php
  src/Entity/Question.php
  src/Entity/Tutorial.php
Labels: Reviewed, Fix

#274 Fix Nombre de réponses correctes
  src/Controller/AdminQuestionController.php
Labels: Reviewed, Fix

#265 alignContain
  assets/styles/lesson.scss
  src/Controller/LessonController.php
  templates/components/_navbar.html.twig
  templates/lesson/index.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Conflicts resolved

#275 Fix : bouton admin s'affiche en xl
  templates/components/_header.html.twig
Labels: Reviewed, Fix

#276 Arrangé front du collection type et supprimé navbar admin
  assets/styles/admin.scss
  src/Controller/AdminController.php
  src/Controller/AdminTutorialController.php
  templates/admin/index.html.twig
  templates/admin_question/edit.html.twig
  templates/components/_form_collection_question.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed, Fix

#278 fix quiz
  assets/styles/quiz.scss
Labels: Reviewed, Fix

#279 fix route admin
  templates/components/_header.html.twig
  templates/login/index.html.twig
Labels: Reviewed, Fix

#269 fix size video
  assets/styles/quiz.scss
  templates/components/_header.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Fix, Conflicts resolved

#277 Fix scroll
  assets/styles/home.scss
  assets/styles/theme.scss
  templates/home/index.html.twig
  templates/home/legal.html.twig
Labels: Reviewed, Fix

#280 fix front admin boutons et overflow
  assets/styles/admin.scss
  config/packages/fos_ckeditor.yaml
  templates/admin_lesson/edit.html.twig
  templates/admin_lesson/new.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_question/new.html.twig
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/admin_tutorial/quiz_index.html.twig
  templates/components/_headerAdmin.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed, Fix

#282 conflicAdmin
  src/Entity/Lesson.php
  src/Entity/Question.php
Labels: Reviewed, Fix

#284 Remis filtre raw pour wysiwig et titre profil en jaune
  templates/lesson/show.html.twig
  templates/profile/profile.html.twig
Labels: Reviewed, Fix

#281 Dev to main 07/02 15h30
  assets/styles/admin.scss
  assets/styles/home.scss
  assets/styles/lesson.scss
  assets/styles/profile.scss
  assets/styles/quiz.scss
  assets/styles/theme.scss
  config/packages/fos_ckeditor.yaml
  src/Controller/AdminController.php
  src/Controller/AdminLessonController.php
  src/Controller/AdminQuestionController.php
  src/Controller/AdminTutorialController.php
  src/Controller/HomeController.php
  src/Controller/LessonController.php
  src/Controller/TutorialController.php
  src/Entity/Lesson.php
  src/Entity/Tutorial.php
  templates/admin/index.html.twig
  templates/admin_lesson/edit.html.twig
  templates/admin_lesson/new.html.twig
  templates/admin_question/edit.html.twig
  templates/admin_question/index.html.twig
  templates/admin_question/new.html.twig
  templates/admin_tutorial/edit.html.twig
  templates/admin_tutorial/index.html.twig
  templates/admin_tutorial/lessons_index.html.twig
  templates/admin_tutorial/new.html.twig
  templates/admin_tutorial/quiz_index.html.twig
  templates/base.html.twig
  templates/bundles/TwigBundle/Exception/error400.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/components/_form_collection_question.html.twig
  templates/components/_header.html.twig
  templates/components/_headerAdmin.html.twig
  templates/components/_navbar.html.twig
  templates/components/_quiz.html.twig
  templates/home/index.html.twig
  templates/home/legal.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  templates/lesson/index.html.twig
  templates/lesson/show.html.twig
  templates/login/index.html.twig
  templates/profile/profile.html.twig
  templates/profile/profile_form.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed

#285 enlevé bouton retour sur menu tuto
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix

#283 Fix boutons admin
  templates/home/legal.html.twig
Labels: Reviewed, Fix

#286 modif de la taille de video ainsi que le quiz
  assets/styles/quiz.scss
  assets/styles/theme.scss
  templates/components/_quiz.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Fix, Conflicts resolved

#288 roundGlobal
  templates/profile/profile.html.twig
Labels: Reviewed, Fix

#289 fix the margin bottom of lesson card
  assets/styles/lesson.scss
  templates/lesson/index.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix

#291 Fixtures
  src/DataFixtures/QuestionFixtures.php
  src/DataFixtures/ResponseFixtures.php
  src/DataFixtures/TutorialFixtures.php
Labels: Reviewed, Fix

#292 buttonDelete
  assets/styles/profile.scss
  src/Form/ProfileType.php
Labels: Reviewed, Fix

#294 fix Fixtures boucles
  src/DataFixtures/ResponseFixtures.php
Labels: Reviewed, Fix

#293 fixHeaderTuto
  templates/components/_header.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix

#290 Fix with validator w3 c
  assets/styles/profile.scss
  templates/home/index.html.twig
  templates/home/legal.html.twig
  templates/login/index.html.twig
  templates/profile/profile.html.twig
  templates/registration/register.html.twig
  templates/tutorial/index.html.twig
Labels: Reviewed, Fix, Conflicts resolved

#295 messageFlashQuizz
  templates/components/_message_flash.html.twig
  templates/lesson/show.html.twig
Labels: Reviewed, Fix

#296 divers fix
  assets/styles/profile.scss
  src/Controller/ProfileController.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/userImages/profile.png
  src/DataFixtures/userImages/profileUser.jpg
  templates/components/_navbar.html.twig
  templates/profile/profile.html.twig
  templates/profile/profile_form.html.twig
Labels: Reviewed, Fix

#298 returnPath_Profil
  templates/profile/profile.html.twig
  templates/profile/profile_form.html.twig
Labels: Reviewed

#297 add margin bottom on each page
  assets/styles/lesson.scss
  assets/styles/profile.scss
  assets/styles/quiz.scss
  templates/lesson/show.html.twig
  templates/profile/profile.html.twig
  templates/profile/profile_form.html.twig
Labels: Fix, Conflicts resolved

#299 fix on the return_path profile
  assets/styles/profile.scss
  templates/profile/profile.html.twig
  templates/profile/profile_form.html.twig
Labels: Reviewed, Fix
